imgix/imgix-rails

- .travis.yml
- README.md
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
**Use case:**
I'm running an application on Heroku and am handling file uploads. We upload the files directly to S3 to get around the low max request times on Heroku. Thus, we store the fully-qualified URLs for images in our database.
I would like a way to have `imgix-rails` drop the protocol and hostname from input paths.
> Allow setting of a :base_path configuration to remove hostnames from URLs

- lib/imgix/rails/view_helper.rb
Hostname replacement was not being applied to alternate resolutions when using the responsive image helper.
> Fix responsive URLs with hostname replacement

- README.md
While integrating this library today, I was initially confused when the configuration option `hostnames_to_remove` wasn't acting as expected. After reading the spec files I noticed the correct configuration variable is `hostnames_to_replace`, so I updated the README to reflect this. 
Thanks for the integration! It's pretty sweet.
> Correcting configuration option name in README.

- lib/imgix/rails/view_helper.rb
In my project I have a @client variable in one of my controller that conflict with the instance variable declared in imgix-rails helpers.
So I prefixed the @client variable with imgix_
> Namespace client variable to avoid conflicts

- lib/imgix/rails/url_helper.rb
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails/url_helper_spec.rb
Target use case: We use imgix-rails in a Serializer.  This will allow a user to use the `ViewHelper` in a Rails View in their app, and also have the `UrlHelper` for their serializers.  Having a seperate `UrlHelper` prevents importing the tag-helpers into one's json serializers, while importing only the `ix_image_url` helper.
> Extract UrlHelper out of ViewHelper

- README.md
- imgix-rails.gemspec
- lib/imgix/rails/url_helper.rb
- spec/imgix/rails/url_helper_spec.rb
- spec/imgix/rails_spec.rb
Probably not worth bumping to 1.0.0 to match imgix-rb, since the only breaking change is from `:secure` to `:use_https` in the config. Maybe 0.4.0 instead? At least this gets the two Ruby libs aligned.
> Updated to use imgix-rb 1.0.0

- lib/imgix/rails/url_helper.rb
Because I have another method called `client` in my app, there is a conflict.
So I prefixed your method by `imgix_`.
I know it is a private method but ... you know private methods in Rails helpers ...
http://stackoverflow.com/questions/12835367/why-can-private-helper-methods-still-be-accessed-in-views
> Prefix client method helper by imgix_

- lib/imgix/rails/image_tag.rb
- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
This PR is intended to ensure that the `widths` option given to the `image_tag()` function doesn't accidentally make its way as a query parameter into either the `srcset` or `src` attributes of the generated image tag.
This PR fixes #43.
@Tailzip @cherifzouein @lucianopanaro @emaraschio I'm not a native Rubyist, so I'd love to get a quick review from one of you before this goes out.
> Keep `widths` option out of image tag query params

- README.md
Each parameter should be seperated with a comma.
> fix(readme): missing comma ix_image_tag example

- lib/imgix/rails/url_helper.rb
- spec/imgix/rails/url_helper_spec.rb
Since imgix-rb supports both host and hosts option (https://github.com/imgix/imgix-rb/blob/master/lib/imgix/client.rb#L12), not sure if you'd like this PR.
It basically sets hosts option for Imgix::Client instead of host if source is an Array.
> Use hosts option when source is an Array

- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
This PR removes `ix_picture_tag`'s `picture_tag_options`, `imgix_default_options` deprecated arguments. It's recommended to use `tag_options` and `url_params` arguments respectively.
This is a **backwards-incompatible** change.
> Remove deprecated ix_picture_tag arguments

- README.md
- lib/imgix/rails/image_tag.rb
- lib/imgix/rails/picture_tag.rb
- lib/imgix/rails/tag.rb
- lib/imgix/rails/url_helper.rb
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails/url_helper_spec.rb
- spec/imgix/rails_spec.rb
This PR adds support for generating URLs across multiple imgix sources. This PR also removes hostname replacement functionality.
This PR adds support for following configuration:
- `:sources` a Hash of imgix source-secure_url_token key-value pairs. If the value for a source is `nil`, URLs generated for the corresponding source won't be secured. This option can't be used with `:source`.
- `:default_source` optionally specify a default source for generating URLs.
Example:
```ruby
Rails.application.configure do
config.imgix = {
sources: {
"assets.imgix.net"  => "foobarbaz",
"assets2.imgix.net" => nil,   # Will generate unsigned URLs
},
default_source: "assets.imgix.net"
}
end
```
`source` optional argument is added to these helpers to support the following usage:
```erb
<%= …
```
> Add support for multiple imgix sources

- README.md
- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
This PR updates the screen sizes used for `srcset` generation in `img` and `picture` tag. The library doesn't maintain a list of standard screen resolutions, and instead calculates screen sizes using the following criteria:
- Smallest size is 100px
- Maximum size is 2560*2=5120px (27" iMac resolution)
- Screen size incremented by 16% consecutively from the smallest size to the maximum size. This gives a tolerance of 8% for the desired image size.
The user can still override the widths by using `widths` parameter.
> Update screen sizes used for srcset generation

- lib/imgix/rails/view_helper.rb
This PR adds proper support for the `widths` option in the `ix_picture_tag` helper, which allows users to override the set of standard widths applied to the `srcset` list for child `<source>` elements. This option's omission from this helper was an unintentional oversight.
> Include `widths` option in picture tag

- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
This PR fixes an issue found in #68, where our `srcset` generation was appending an extra widthless source to the end of its list, ostensibly as a "fallback image". This is incorrect: all URLs provided in a `srcset` must be accompanied a size description, and the "fallback image" in this scenario is provided by the element's `src` attribute.
This PR fixes #68.
> Remove trailing widthless src in srcset generation

- .travis.yml
- imgix-rails.gemspec
gemspec modified to allow bundler versions 1.9 through 3.0 (non inclusive) as a dev dependency. This way, users on 2.0 will not be forced to downgrade for development purposes.
Fixes bug #70
> Update bundler dev dependency to include new major version 2.x

- imgix-rails.gemspec
- spec/imgix/rails/url_helper_spec.rb
Resolves #75 
This PR updates the `imgix-rb` runtime dependency to use the latest major version. However, this does introduce a breaking change to this gem since the dependency no longer supports the use of the `hosts` argument used in domain sharding.
> chore(deps): upgrade imgix-rb to ~> 3.0

- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
This PR removes the logic in `ix_image_tag` responsible for resizing the `h` (height) parameter to maintain aspect ratio when building the `srcset` attribute. With the help of the [imgix aspect ratio parameter](https://blog.imgix.com/2019/07/17/aspect-ratio-parameter-makes-cropping-even-easier), users can now achieve the same effect with the inclusion of the `ar` parameter. Please note, the `ar` parameter should also be used with `fit=crop` to take effect. This should yield slightly better performance, code cleanliness, and bring the gem more in line with the imgix API.
----------
**Demo**
```ruby
<%= ix_image_tag('/demo.jpg', url_params: { w: 1000, ar: '2:1', fit: 'crop'} %>
```
Will produce an image cropped to the specified ratio:
|        | Example srcset URL …
> fix: deprecate resizing height when maintaining aspect ratio

- lib/imgix/rails/picture_tag.rb
- lib/imgix/rails/tag.rb
When doing some analysis on my Rails app (using https://github.com/nevir/Bumbler) errors were being thrown without explicitly requiring ActionView.  
Adding these lines fixed the errors, and should generally make testing imgix-rails in isolation more resilient.
> Add explicit ActionView requires

- README.md
- lib/imgix/rails/picture_tag.rb
- lib/imgix/rails/tag.rb
- lib/imgix/rails/url_helper.rb
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
This PR offloads all of heavy lifting when building `srcset` attributes onto the imgix-rb gem, which has recently received a massive upgrade to support various forms of `srcset` building/customization. These changes only apply to `ix_image_tag` and `ix_picture_tag`:
-  Eliminates the need to calculate/filter `standard_widths`, which are now just generated by the underlying imgix-rb gem. This yields a much cleaner codebase.
- Includes the addition of [fixed-sized srcsets](https://github.com/imgix/imgix-rb#fixed-image-rendering) which allows users to serve the same size image at different resolutions. 
- This also includes a handy new feature called [variable qualities](https://github.com/imgix/imgix-rb#variable-qualities) which can help maximize the quality to image weight ratio.
- …
> feat: utilize Imgix::Path#to_srcset when constructing srcsets

- README.md
In preparation for the release of v4.0.0, this guide will help users migrate to the newest version and navigate any breaking-changes in the process.
> docs: add upgrade guide for v3.x to v4

- imgix-rails.gemspec
This PR adds [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. The project metadata allows users to more easily access the source code, raise issues, and view the changelog directly from the [imgix-rails page](https://rubygems.org/gems/imgix-rails) on rubygems. These fields will also be accessible via the rubygems API.
> docs: add project metadata to gemspec

- README.md
- spec/imgix/rails/url_helper_spec.rb
- spec/imgix/rails_spec.rb
First of all, thank you for fantastic service & gem!
This PR adds document and test for `include_library_param` option.
This option configurable and useful, but that seems hasn't been documented and tested yet.
> docs: add description and tests for include_library_param option

- README.md
This PR serves as a follow up to #87. It wraps the subheader describing each helper method in backticks to prevent unintentional italicization when pulled into the SDK [docs page](https://docs.imgix.com/libraries).
> docs: wrap helper method subheaders in code block

- lib/imgix/rails/url_helper.rb
- spec/imgix/rails/url_helper_spec.rb
The purpose of this PR is to resolve deprecation warnings being thrown
as a result of using `imgix-rb` version `3.3.0`, see [here](https://github.com/imgix/imgix-rb/pull/76).
> fix: replace opts[:host] with opts[:domain] to suppress deprecated warnings

- imgix-rails.gemspec
The purpose of this PR is to update the `imgix` version to `~> 4.0`.
> chore: update to imgix 4.0

- README.md
This PR adds a subsection under the `ix_image_url` docs, detailing how to use the helper function outside of the context of a view. This fixes #77 by increasing discoverability and clarity of this use case.
> docs: update usage example

- README.md
- lib/imgix/rails/image_tag.rb
- lib/imgix/rails/tag.rb
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
Adds lazy support to `ix_image_tag` as described on #60. We need this in our project due to the amount of images being loaded on a single webpage, often from very bad network scenarios.
Add `lazy: true` to an ix_image_tag:
```erb
<%= ix_image_tag 'image.jpg', lazy: true %>
```
Set an image to `lazy` to use it instead:
```erb
<%= ix_image_tag 'image.jpg', lazy: asset_pack_url('loading.gif') %>
```
Related issue: #60
> Add support for lazy image loading

- README.md
- lib/imgix/rails/picture_tag.rb
- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
As suggested in #40 and #101, this PR adds an `img_tag_options` argument for `ix_picture_tag`. This can be used to futher customize the generated tags. It also updates the specs and README for documentation.
You can check the spec changes to see how this can be used.
Since this only adds an additional optional parameter, I don't expect any incompatibilities and therefore would **not** consider this a breaking change.
> feat: add img_tag_options to ix_picture_tag

- README.md
- lib/imgix/rails/url_helper.rb
- spec/imgix/rails/url_helper_spec.rb
This is a very simple attempt at fixing https://github.com/imgix/imgix-rails/issues/124
Already URL-encoded URLs generated by Paperclip were URL-encoded twice thus generating 404s and the `?` in URLs with asset fingerprint in the query was URL-encoded again generating 404s.
By passing `disable_path_encoding: true` it's possible to skip URL-encoding in `imgix_image_url`. Examples can be seen in added specs.
> Expose disable path encoding on `imgix_image_url`

- .circleci/config.yml
JRuby bundler version needs to be specified for CircleCI to be able to install and run bundler.
> build: fix circle config

- README.md
Correct readme instructions to use "&" instead of "&amp;" to chain parameters.
Same for output HTML code snippets.
> fix(readme):remove html encoding from parameter strings
