- lib/imgix/rails/view_helper.rb
- spec/imgix/rails_spec.rb
Hey @kellysutton, we discussed this briefly in the Spec Slack. Here's that PR I was talking about.
-paul
> Added Imgix::Rails::ViewHelper#ix_image_url

- README.md
Noticed the typo while running through readme (:
> Deafults typo corrected to Defaults.

- README.md
In a recent project we used the `ix_image_url` method a good bit and found it very useful, so I figured it might be good to have some public documentation. Let me know what you think!
> Documenting ix_image_url method.

- README.md
- lib/imgix/rails/view_helper.rb
Documenting the split from #13
> Document new UrlHelper functionality

- README.md
Hey @kellysutton, mind doing a once-over?
> Add Paperclip and Refile examples to readme

- README.md
- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
Hey @kellysutton, any thoughts on this?
> Add auto-width-multiple-adding + specific widths.

- .travis.yml
- lib/imgix/rails/tag.rb
- spec/imgix/rails_spec.rb
> Include `widths` in filtered parameters

- README.md
- lib/imgix/railtie.rb
> Add UrlHelper to Sprockets::Context if present.

- .travis.yml
- README.md
Hello. I've copied the ActiveStorage instructions in [this comment](https://github.com/imgix/imgix-rails/issues/72#issuecomment-484726636) and popped them in the README.md to make them easier to find.
> docs: add ActiveStorage instructions to README

- README.md
As a follow up to #87, revise the project headline to match the rest of imgix's SDK libraries.
> docs: revise project headline in README

- README.md
As a follow up to #87, changes the gem version badge.
> docs: change gem version badge; style changes

- CHANGELOG.md
- lib/imgix/rails/version.rb
This PR is to release the changes in #94.
> chore(release): 4.0.1

- README.md
- imgix-rails.gemspec
This PR follows up on the branch changes with some changes that were missed initially.
> chore: update some more refs to master

- imgix-rails.gemspec
> build: use optimistic constraint for imgix >= 3.0

- .circleci/config.yml
- .travis.yml
- Gemfile
- imgix-rails.gemspec
This PR replaces the Travis CI config with an equivalent CircleCI config
> chore: use CircleCI

- CONTRIBUTING.md
- README.md
> chore: update contributing guidelines

- CHANGELOG.md
- lib/imgix/rails/version.rb
> chore(release): 4.3.0

- .circleci/config.yml
> ci: deprecate ruby 2.6, add 3.1

- README.md
> chore: update test versions in readme

- CHANGELOG.md
- lib/imgix/rails/version.rb
> chore(release): v4.3.1
